AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./demo
      Handler: test.lambda_handler
      Runtime: python3.9
      Timeout: 10
      MemorySize: 128
